eureka_g6k_admin:
    path:     /admin
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\HomeAdminController::index }

eureka_g6k_admin_documentation:
    path:     /admin/doc/{document}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\DocumentationController::index }

eureka_g6k_admin_clear_cache:
    path:     /admin/cache/clear
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\CacheAdminController::clear }

eureka_g6k_admin_clear_cache_env:
    path:     /admin/cache/clear/{env}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\CacheAdminController::clear }

eureka_g6k_admin_warmup_cache:
    path:     /admin/cache/warmup
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\CacheAdminController::warmup }


eureka_g6k_admin_datasources:
    path:     /admin/datasources
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\DataSourcesAdminController::index }

eureka_g6k_admin_datasource:
    path:     /admin/datasources/{dsid}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\DataSourcesAdminController::index }

eureka_g6k_admin_datasource_table:
    path:     /admin/datasources/{dsid}/{table}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\DataSourcesAdminController::index }

eureka_g6k_admin_datasource_crud:
    path:     /admin/datasources/{dsid}/{table}/{crud}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\DataSourcesAdminController::index }

eureka_g6k_admin_users:
    path:     /admin/users
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\UsersAdminController::index }

eureka_g6k_admin_user_crud:
    path:     /admin/users/{crud}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\UsersAdminController::index }

eureka_g6k_admin_simulators:
    path:     /admin/simulators
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\SimulatorsAdminController::index }

eureka_g6k_admin_simulator:
    path:     /admin/simulators/{simulator}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\SimulatorsAdminController::index }

eureka_g6k_admin_simulator_crud:
    path:     /admin/simulators/{simulator}/{crud}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\SimulatorsAdminController::index }

eureka_g6k_admin_views:
    path:     /admin/views
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\ViewsAdminController::index }

eureka_g6k_admin_view:
    path:     /admin/views/{view}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\ViewsAdminController::index }

eureka_g6k_admin_view_node:
    path:     /admin/views/{view}/{node}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\ViewsAdminController::index }

eureka_g6k_admin_view_node_crud:
    path:     /admin/views/{view}/{node}/{crud}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\ViewsAdminController::index }

eureka_g6k_admin_pdfforms:
    path:     /admin/pdfforms
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\PDFFormsAdminController::index }

eureka_g6k_admin_pdfform:
    path:     /admin/pdfforms/{pdf}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\PDFFormsAdminController::index }

eureka_g6k_admin_pdfform_crud:
    path:     /admin/pdfforms/{pdf}/{crud}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\PDFFormsAdminController::index }

eureka_g6k_admin_simulator_calcul:
    path:     /{simu}/{view}/tryIt
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\DefaultController::tryIt }

eureka_g6k_admin_simulator_regional_settings:
    path:     /admin/regional-settings/{locale}
    methods: [ get ]
    defaults: { _controller: App\G6K\Controller\SimulatorsAdminController::regionalSettings }

eureka_g6k_admin_simulator_validate:
    path:     /admin/validate
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\SimulatorsAdminController::validate }

eureka_g6k_index:
    path:     /
    methods: [ get ]
    defaults: { _controller: App\G6K\Controller\IndexController::index }

eureka_g6k_fields:
    path:     /{simu}/Default/fields
    methods: [ post ]
    defaults: { _controller: App\G6K\Controller\DefaultController::fields }

eureka_g6k_fields_try:
    path:     /{simu}/tryIt/Default/fields
    methods: [ post ]
    defaults: { _controller: App\G6K\Controller\DefaultController::fieldsTryIt }

eureka_g6k_source:
    path:     /{simu}/Default/source
    methods: [ post ]
    defaults: { _controller: App\G6K\Controller\DefaultController::source }

eureka_g6k_source_try:
    path:     /{simu}/tryIt/Default/source
    methods: [ post ]
    defaults: { _controller: App\G6K\Controller\DefaultController::sourceTryIt }

eureka_g6k_calcul:
    path:     /{simu}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\DefaultController::calcul }

eureka_g6k_api:
    path:     /{simu}/api
    methods: [ get ]
    defaults: { _controller: App\G6K\Controller\APIController::calcul }

eureka_g6k_calcul_view:
    path:     /{simu}/{view}
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\DefaultController::calcul }

eureka_g6k_calcul_api_try:
    path:     /{simu}/api/tryIt
    methods: [ get ]
    defaults: { _controller: App\G6K\Controller\APIController::tryIt }

eureka_g6k_calcul_view_try:
    path:     /{simu}/{view}/tryIt
    methods: [ get, post ]
    defaults: { _controller: App\G6K\Controller\DefaultController::tryIt }

eureka_g6k_mail_send:
    path:     /{template}/{view}/mail
    methods: [ post ]
    defaults: { _controller: App\G6K\Controller\MailController::sendMail }

